-- Yuniko schema for the Supabase PostgreSQL project.
-- Source: lib/db/src/schema/*.ts
-- The Yuniko API continues to own authentication/session state with its JWT system.

create table if not exists public.users (id serial primary key, username text not null unique, display_name text not null, password_hash text not null, country text, country_flag text, age integer, avatar_url text, bio text not null default '', website text, verification_status text not null default 'none', verification_requested_at timestamp, created_at timestamp not null default now());
create table if not exists public.posts (id serial primary key, user_id integer not null references public.users(id) on delete cascade, caption text not null default '', media_url text, media_type text not null default 'image', media_items text, location text, hashtags text, is_world_feed boolean not null default true, likes integer not null default 0, comments integer not null default 0, shares integer not null default 0, saves integer not null default 0, reposts integer not null default 0, views integer not null default 0, reports integer not null default 0, viral_score integer not null default 0, distribution_tier integer not null default 0, distribution_countries text not null default '[]', created_at timestamp not null default now(), updated_at timestamp not null default now());
create table if not exists public.post_engagements (id serial primary key, post_id integer not null references public.posts(id) on delete cascade, user_id integer not null references public.users(id) on delete cascade, liked boolean not null default false, saved boolean not null default false, shared boolean not null default false, reposted boolean not null default false, reported boolean not null default false, view_count integer not null default 0, watch_ms integer not null default 0, completion_rate integer not null default 0, countries_seeded text, last_viewed_at timestamp, created_at timestamp not null default now(), updated_at timestamp not null default now());
create unique index if not exists post_engagements_user_post_idx on public.post_engagements(user_id, post_id);
create index if not exists post_engagements_reposted_idx on public.post_engagements(post_id, reposted);
create table if not exists public.stories (id serial primary key, user_id integer not null references public.users(id), media_url text not null, media_type text not null default 'image', caption text not null default '', expires_at timestamp not null, created_at timestamp not null default now());
create table if not exists public.comments (id serial primary key, post_id integer not null references public.posts(id) on delete cascade, user_id integer not null references public.users(id), text text not null, created_at timestamp not null default now());
create table if not exists public.follows (id serial primary key, follower_id integer not null references public.users(id) on delete cascade, following_id integer not null references public.users(id) on delete cascade, is_friend boolean not null default false, created_at timestamp not null default now());
create unique index if not exists follows_follower_following_idx on public.follows(follower_id, following_id);
create table if not exists public.notifications (id serial primary key, user_id integer not null references public.users(id) on delete cascade, actor_id integer references public.users(id) on delete cascade, type text not null, post_id integer references public.posts(id) on delete cascade, story_id integer references public.stories(id) on delete cascade, message text not null, read_at timestamp, created_at timestamp not null default now());
create table if not exists public.conversations (id serial primary key, created_at timestamp not null default now(), updated_at timestamp not null default now());
create table if not exists public.conversation_members (id serial primary key, conversation_id integer not null references public.conversations(id) on delete cascade, user_id integer not null references public.users(id) on delete cascade, last_read_at timestamp, muted boolean not null default false);
create unique index if not exists conversation_members_member_idx on public.conversation_members(conversation_id, user_id);
create table if not exists public.messages (id serial primary key, conversation_id integer not null references public.conversations(id) on delete cascade, sender_id integer not null references public.users(id) on delete cascade, kind text not null default 'text', body text not null default '', media_url text, duration_ms integer, delivered_at timestamp not null default now(), read_at timestamp, created_at timestamp not null default now());
create table if not exists public.message_requests (id serial primary key, sender_id integer not null references public.users(id) on delete cascade, recipient_id integer not null references public.users(id) on delete cascade, message text not null default '', status text not null default 'pending', created_at timestamp not null default now(), updated_at timestamp not null default now());
create unique index if not exists message_requests_sender_recipient_idx on public.message_requests(sender_id, recipient_id);
create table if not exists public.blocked_users (id serial primary key, blocker_id integer not null references public.users(id) on delete cascade, blocked_id integer not null references public.users(id) on delete cascade, created_at timestamp not null default now());
create unique index if not exists blocked_users_blocker_blocked_idx on public.blocked_users(blocker_id, blocked_id);
create table if not exists public.archived_conversations (id serial primary key, conversation_id integer not null references public.conversations(id) on delete cascade, user_id integer not null references public.users(id) on delete cascade, archived_at timestamp not null default now());
create unique index if not exists archived_conversations_user_conversation_idx on public.archived_conversations(user_id, conversation_id);
create table if not exists public.story_views (id serial primary key, story_id integer not null references public.stories(id) on delete cascade, user_id integer not null references public.users(id) on delete cascade, viewed_at timestamp not null default now());
create unique index if not exists story_views_story_user_idx on public.story_views(story_id, user_id);
create table if not exists public.story_reactions (id serial primary key, story_id integer not null references public.stories(id) on delete cascade, user_id integer not null references public.users(id) on delete cascade, emoji text not null, created_at timestamp not null default now());
create unique index if not exists story_reactions_story_user_idx on public.story_reactions(story_id, user_id);
create table if not exists public.story_replies (id serial primary key, story_id integer not null references public.stories(id) on delete cascade, user_id integer not null references public.users(id) on delete cascade, text text not null, created_at timestamp not null default now());
create table if not exists public.calls (id text primary key, caller_id integer not null references public.users(id) on delete cascade, target_user_id integer not null references public.users(id) on delete cascade, kind text not null, status text not null default 'ringing', started_at timestamp, ended_at timestamp, created_at timestamp not null default now());
create table if not exists public.call_signals (id serial primary key, call_id text not null references public.calls(id) on delete cascade, sender_id integer not null references public.users(id) on delete cascade, type text not null, payload text not null, created_at timestamp not null default now());
create table if not exists public.live_sessions (id serial primary key, host_user_id integer not null references public.users(id) on delete cascade, title text not null default '', stream_url text, status text not null default 'live', is_public boolean not null default true, started_at timestamp not null default now(), ended_at timestamp);
create table if not exists public.live_engagements (id serial primary key, live_id integer not null references public.live_sessions(id) on delete cascade, user_id integer not null references public.users(id) on delete cascade, liked boolean not null default false, shared boolean not null default false, updated_at timestamp not null default now());
create unique index if not exists live_engagements_live_user_unique on public.live_engagements(live_id, user_id);
create table if not exists public.live_comments (id serial primary key, live_id integer not null references public.live_sessions(id) on delete cascade, user_id integer not null references public.users(id) on delete cascade, text text not null, created_at timestamp not null default now());
create table if not exists public.feedback (id serial primary key, user_id integer not null references public.users(id) on delete cascade, category text not null, message text not null, rating integer not null default 0, created_at timestamp not null default now());
create table if not exists public.user_settings (id serial primary key, user_id integer not null unique references public.users(id) on delete cascade, private_account boolean not null default false, read_receipts boolean not null default true, message_permission text not null default 'everyone', comment_permission text not null default 'everyone', story_permission text not null default 'friendsOnly', hidden_post_ids text not null default '[]', updated_at timestamp not null default now());

insert into storage.buckets (id, name, public) values ('media', 'media', true) on conflict (id) do update set public = true;

do $$ declare t text; begin foreach t in array array['users','posts','post_engagements','stories','comments','follows','notifications','conversations','conversation_members','messages','message_requests','blocked_users','archived_conversations','story_views','story_reactions','story_replies','calls','call_signals','live_sessions','live_engagements','live_comments','feedback','user_settings'] loop execute format('alter table public.%I enable row level security', t); end loop; end $$;
