import { useEffect,useState } from "react";
import { useLocation } from "wouter";
import { ArrowLeft,Search,UserPlus,X } from "lucide-react";
import { apiJson } from "@/lib/api";
import { t } from "@/lib/i18n";
import BottomNav from "@/components/BottomNav";

type User={id:number;username:string;displayName:string;avatarUrl:string|null};
export default function AddFriends(){const [,setLocation]=useLocation();const [query,setQuery]=useState("");const [users,setUsers]=useState<User[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [following,setFollowing]=useState<Set<number>>(new Set());
 useEffect(()=>{const q=query.trim().replace(/^@/,"");if(q.length<1){setUsers([]);setError("");setLoading(false);return;}let active=true;setLoading(true);setError("");const timer=window.setTimeout(()=>apiJson<{users:User[]}>(`/users/search?q=${encodeURIComponent(q)}`).then(d=>active&&setUsers(Array.isArray(d.users)?d.users:[])).catch(err=>{if(!active)return;setUsers([]);setError(err instanceof Error?err.message:"Search failed")}).finally(()=>active&&setLoading(false)),250);return()=>{active=false;window.clearTimeout(timer);};},[query]);
 const toggle=async(id:number)=>{const is=following.has(id);const d=await apiJson<{following:boolean}>(`/users/${id}/follow`,{method:is?"DELETE":"POST"}).catch(()=>null);if(d)setFollowing(prev=>{const n=new Set(prev);d.following?n.add(id):n.delete(id);return n;});};
 const normalizedQuery=query.trim().replace(/^@/,"");
 return <div className="w-full max-w-[430px] mx-auto min-h-screen bg-background pb-20"><header className="sticky top-0 z-40 px-4 py-4 flex items-center gap-3 bg-black/95 border-b border-white/5"><button onClick={()=>setLocation("/")}><ArrowLeft size={22} className="text-white/80"/></button><h1 className="text-base font-semibold text-white flex-1">{t("addFriends")}</h1></header><div className="px-4 py-3"><div className="flex items-center gap-2.5 px-3 py-2.5 rounded-2xl bg-white/[.06] border border-white/[.08]"><Search size={16} className="text-white/40"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t("searchUsers")} className="flex-1 bg-transparent text-white/80 text-sm outline-none placeholder:text-white/30" autoFocus/>{query&&<button onClick={()=>setQuery("")}><X size={14} className="text-white/40"/></button>}</div>{loading&&<p className="py-6 text-center text-white/40 text-sm">Searching...</p>}{!loading&&error&&<p className="py-12 text-center text-red-400 text-sm">{error}</p>}{!loading&&!error&&normalizedQuery.length<1&&<div className="flex flex-col items-center py-16 gap-3"><UserPlus size={42} className="text-white/20"/><p className="text-white/40 text-sm">Search for real Yuniko users</p></div>}{!loading&&!error&&normalizedQuery.length>=1&&users.length===0&&<p className="py-12 text-center text-white/40 text-sm">No users found</p>}{users.map(u=>{const isFollowing=following.has(u.id);const av=u.avatarUrl??`https://api.dicebear.com/8.x/initials/svg?seed=${encodeURIComponent(u.displayName)}&backgroundColor=FF006E`;return <div key={u.id} className="flex items-center gap-3 py-3 border-b border-white/5"><button onClick={()=>setLocation(`/user/${u.id}`)}><img src={av} alt={u.displayName} className="w-11 h-11 rounded-full object-cover"/></button><button onClick={()=>setLocation(`/user/${u.id}`)} className="flex-1 min-w-0 text-left"><p className="text-white font-semibold text-sm">{u.displayName}</p><p className="text-white/50 text-xs">@{u.username}</p></button><button onClick={()=>toggle(u.id)} className="px-4 py-1.5 rounded-full text-sm font-semibold text-white" style={{background:isFollowing?"rgba(255,255,255,.1)":"linear-gradient(135deg,#FF006E,#8B00FF)"}}>{isFollowing?t("following"):t("follow")}</button></div>})}</div><BottomNav/></div>;
}
