import { useEffect,useState } from "react";
import { useLocation,useParams } from "wouter";
import { ArrowLeft,Hash } from "lucide-react";
import { apiJson } from "@/lib/api";
import BottomNav from "@/components/BottomNav";

type Post={id:number;mediaUrl:string|null;caption:string;mediaType:string;hashtags?:string;createdAt:string};
export default function Hashtag(){const [,setLocation]=useLocation();const params=useParams<{tag:string}>();const tag=(params?.tag??"trending").replace(/^#/ ,"");const [posts,setPosts]=useState<Post[]>([]);const [loading,setLoading]=useState(true);
 useEffect(()=>{apiJson<{posts:Post[]}>(`/users/search?q=${encodeURIComponent(tag)}`).then(d=>{const needle=tag.toLowerCase();setPosts((d.posts??[]).filter(p=>(p.hashtags??"").toLowerCase().includes(needle)||p.caption.toLowerCase().includes(`#${needle}`)).slice(0,60));}).catch(()=>setPosts([])).finally(()=>setLoading(false));},[tag]);
 return <div className="w-full max-w-[430px] mx-auto min-h-screen bg-background pb-20"><header className="sticky top-0 z-40 px-4 py-4 flex items-center gap-3 bg-black/95 border-b border-white/5"><button onClick={()=>window.history.back()}><ArrowLeft size={22} className="text-white/80"/></button><h1 className="text-base font-semibold text-white">#{tag}</h1></header><div className="px-4 py-6 flex flex-col items-center gap-3 border-b border-white/5"><div className="w-20 h-20 rounded-full flex items-center justify-center bg-pink-500/10 border-2 border-pink-500/30"><Hash size={36} className="text-pink-400"/></div><h2 className="text-2xl font-bold text-white">#{tag}</h2><p className="text-white/50 text-sm">{posts.length} matching posts</p></div>{loading?<div className="py-20 text-center text-white/40">Loading...</div>:posts.length===0?<div className="py-20 text-center text-white/40">No posts found for #{tag}</div>:<div className="grid grid-cols-3 gap-0.5 px-0.5 pt-1">{posts.map(p=><button key={p.id} onClick={()=>setLocation(`/post/live_${p.id}`)} className="aspect-square overflow-hidden">{p.mediaUrl?<img src={p.mediaUrl} alt={p.caption} loading="lazy" className="w-full h-full object-cover"/>:<div className="w-full h-full flex items-center justify-center p-2 text-white/60 text-xs">{p.caption}</div>}</button>)}</div>}<BottomNav/></div>;
}
