import { Router, Request } from "express";
import { postsTable, commentsTable, postEngagementsTable, notificationsTable, usersTable } from "@workspace/db/schema";
import { db } from "@workspace/db";
import { and, eq, desc, sql } from "drizzle-orm";
import { authMiddleware } from "../middlewares/auth";
import { nonNegativeInt, positiveId, textField } from "../middlewares/validation";
import { rankFeedSignal } from "../infrastructure/feed-ranking";

const postsRouter = Router();
type AuthedRequest = Request & { userId?: number };
const INITIAL_COUNTRIES = 3;
const EXPANDED_COUNTRIES = 10;
const EXPAND_SCORE = 30;
const WORLD_SCORE = 100;
const GLOBAL_COUNTRIES = ["Afghanistan","Albania","Algeria","Andorra","Angola","Antigua and Barbuda","Argentina","Armenia","Australia","Austria","Azerbaijan","Bahamas","Bangladesh","Barbados","Belarus","Belgium","Belize","Benin","Bhutan","Bolivia","Bosnia and Herzegovina","Botswana","Brazil","Brunei","Bulgaria","Burkina Faso","Burundi","Cabo Verde","Cambodia","Cameroon","Canada","Central African Republic","Chad","Chile","China","Colombia","Comoros","Congo","Costa Rica","Croatia","Cuba","Cyprus","Czechia","Denmark","Djibouti","Dominica","Dominican Republic","Ecuador","Egypt","El Salvador","Equatorial Guinea","Eritrea","Estonia","Eswatini","Ethiopia","Fiji","Finland","France","Gabon","Gambia","Georgia","Germany","Ghana","Greece","Grenada","Guatemala","Guinea","Guinea-Bissau","Guyana","Haiti","Honduras","Hungary","Iceland","India","Indonesia","Iran","Ireland","Israel","Italy","Ivory Coast","Jamaica","Japan","Jordan","Kazakhstan","Kenya","Kiribati","Kuwait","Laos","Latvia","Lebanon","Lesotho","Liberia","Libya","Liechtenstein","Lithuania","Luxembourg","Madagascar","Malawi","Malaysia","Maldives","Mali","Malta","Marshall Islands","Mauritania","Mauritius","Mexico","Micronesia","Moldova","Monaco","Mongolia","Montenegro","Morocco","Mozambique","Myanmar","Namibia","Nauru","Nepal","Netherlands","New Zealand","Nicaragua","Niger","Nigeria","North Korea","North Macedonia","Norway","Oman","Pakistan","Palau","Panama","Papua New Guinea","Paraguay","Peru","Philippines","Poland","Portugal","Qatar","Romania","Russia","Rwanda","Saint Kitts and Nevis","Saint Lucia","Saint Vincent and the Grenadines","Samoa","San Marino","Sao Tome and Principe","Saudi Arabia","Senegal","Serbia","Seychelles","Sierra Leone","Singapore","Slovakia","Slovenia","Somalia","South Africa","South Korea","South Sudan","Spain","Sri Lanka","Sudan","Suriname","Sweden","Switzerland","Syria","Taiwan","Tajikistan","Tanzania","Thailand","Timor-Leste","Togo","Tonga","Tunisia","Turkey","Turkmenistan","Tuvalu","Uganda","Ukraine","United Arab Emirates","United Kingdom","United States","Uruguay","Vanuatu","Vatican City","Venezuela","Vietnam","Yemen","Zambia","Zimbabwe"];
function dbError(res: any, err: unknown) { console.error(err); return res.status(500).json({ error: "Server error" }); }
function parseMediaItems(value: unknown) { if (!Array.isArray(value)) return null; const clean = value.filter((x): x is string => typeof x === "string" && x.trim().length > 0).slice(0, 10); if (clean.some(x => x.length > 1_500_000)) return null; return clean.length ? JSON.stringify(clean) : null; }
function mediaTypeFor(url?: string | null, items?: string | null, requested?: unknown) { if (typeof requested === "string" && ["image","video","carousel","text"].includes(requested)) return requested; if (items) return "carousel"; if (!url) return "text"; return /\.(mp4|mov|webm|m4v)(\?|$)/i.test(url) || url.startsWith("data:video") ? "video" : "image"; }
async function engagementFor(userId:number, postId:number) { const [row] = await db.select().from(postEngagementsTable).where(and(eq(postEngagementsTable.userId,userId),eq(postEngagementsTable.postId,postId))).limit(1); return row; }
async function createNotification(userId:number, actorId:number, type:string, postId:number|null, message:string) { if(userId===actorId)return; await db.insert(notificationsTable).values({userId,actorId,type,postId,message}).catch(()=>undefined); }
function availableCountries(authorCountry?:string|null) { const author=authorCountry?.trim(); if(author&&GLOBAL_COUNTRIES.includes(author)) return [author,...GLOBAL_COUNTRIES.filter(c=>c!==author)]; return [...GLOBAL_COUNTRIES]; }
function calculateViralScore(p:{likes:number;shares:number;comments:number;views:number}) { return rankFeedSignal(p).score; }
async function refreshDistribution(postId:number) { const [post]=await db.select().from(postsTable).where(eq(postsTable.id,postId)).limit(1); if(!post||!post.isWorldFeed)return post; const score=calculateViralScore(post); const tier=score>=WORLD_SCORE?2:score>=EXPAND_SCORE?1:0; const [author]=await db.select({country:usersTable.country}).from(usersTable).where(eq(usersTable.id,post.userId)).limit(1); const countries=availableCountries(author?.country); const distribution=tier===2?GLOBAL_COUNTRIES:tier===1?countries.slice(0,EXPANDED_COUNTRIES):countries.slice(0,INITIAL_COUNTRIES); const [updated]=await db.update(postsTable).set({viralScore:score,distributionTier:tier,distributionCountries:JSON.stringify(distribution),updatedAt:new Date()}).where(eq(postsTable.id,postId)).returning(); return updated; }
postsRouter.post("/posts",authMiddleware,async(req:AuthedRequest,res)=>{const userId=req.userId!;const body=req.body;if(!body||typeof body!=="object"||Array.isArray(body))return res.status(400).json({error:"Invalid request body"});const {caption,mediaUrl,mediaItems,location,hashtags,isWorldFeed,mediaType}=body;const cleanCaption=textField(caption,5000)||"";const serialized=parseMediaItems(mediaItems);if(caption!==undefined&&cleanCaption===null)return res.status(400).json({error:"Caption is too long"});if(mediaItems!==undefined&&serialized===null)return res.status(400).json({error:"Invalid media items"});if(mediaUrl!==undefined&&mediaUrl!==null&&typeof mediaUrl!=="string")return res.status(400).json({error:"Invalid media URL"});if(typeof mediaUrl==="string"&&mediaUrl.length>1_500_000)return res.status(400).json({error:"Media URL is too long"});if(location!==undefined&&(typeof location!=="string"||location.trim().length>200))return res.status(400).json({error:"Invalid location"});if(hashtags!==undefined&&(typeof hashtags!=="string"||hashtags.trim().length>1000))return res.status(400).json({error:"Invalid hashtags"});if(isWorldFeed!==undefined&&typeof isWorldFeed!=="boolean")return res.status(400).json({error:"Invalid world feed flag"});if(mediaType!==undefined&&(!["image","video","carousel","text"].includes(String(mediaType))))return res.status(400).json({error:"Invalid media type"});if(!cleanCaption&&!mediaUrl&&!serialized)return res.status(400).json({error:"Post text, photo, or video required"});try{const [author]=await db.select({country:usersTable.country}).from(usersTable).where(eq(usersTable.id,userId)).limit(1);if(!author)return res.status(401).json({error:"User not found"});const countries=availableCountries(author.country);const [post]=await db.insert(postsTable).values({userId,caption:cleanCaption,mediaUrl:mediaUrl??null,mediaItems:serialized,mediaType:mediaTypeFor(mediaUrl,serialized,mediaType),location:typeof location==="string"?location.trim()||null:null,hashtags:typeof hashtags==="string"?hashtags.trim()||null:null,isWorldFeed:isWorldFeed??true,distributionTier:0,distributionCountries:JSON.stringify(countries.slice(0,INITIAL_COUNTRIES))}).returning();return res.status(201).json({post});}catch(e){return dbError(res,e);}});
postsRouter.get("/posts/feed",authMiddleware,async(req:AuthedRequest,res)=>{const userId=req.userId!;const initialCursor=nonNegativeInt(req.query.cursor,0,Number.MAX_SAFE_INTEGER);const limit=nonNegativeInt(req.query.limit,20,50)||20;try{const base=db.select({id:postsTable.id,userId:postsTable.userId,caption:postsTable.caption,mediaUrl:postsTable.mediaUrl,mediaType:postsTable.mediaType,mediaItems:postsTable.mediaItems,location:postsTable.location,hashtags:postsTable.hashtags,isWorldFeed:postsTable.isWorldFeed,likes:postsTable.likes,comments:postsTable.comments,shares:postsTable.shares,saves:postsTable.saves,views:postsTable.views,reports:postsTable.reports,viralScore:postsTable.viralScore,distributionTier:postsTable.distributionTier,distributionCountries:postsTable.distributionCountries,createdAt:postsTable.createdAt,authorDisplayName:usersTable.displayName,authorUsername:usersTable.username,authorAvatarUrl:usersTable.avatarUrl,liked:postEngagementsTable.liked,saved:postEngagementsTable.saved}).from(postsTable).innerJoin(usersTable,eq(postsTable.userId,usersTable.id)).leftJoin(postEngagementsTable,and(eq(postEngagementsTable.postId,postsTable.id),eq(postEngagementsTable.userId,userId)));const candidates=initialCursor>0?await base.where(sql`${postsTable.id}<${initialCursor}`).orderBy(desc(postsTable.id)).limit(limit):await base.orderBy(desc(postsTable.id)).limit(limit);const nextCursor=candidates.length===limit?candidates[candidates.length-1].id:null;return res.json({posts:candidates,nextCursor,hasMore:candidates.length===limit});}catch(e){return dbError(res,e);}});
function postIdFrom(req:Request,res:any){const id=positiveId(req.params.id);if(!id)res.status(400).json({error:"Invalid post id"});return id;}
postsRouter.patch("/posts/:id",authMiddleware,async(req:AuthedRequest,res)=>{const id=postIdFrom(req,res);if(!id)return;const body=req.body;if(!body||typeof body!=="object"||Array.isArray(body))return res.status(400).json({error:"Invalid request body"});const {caption,location,hashtags}=body;if(caption!==undefined&&textField(caption,5000)===null)return res.status(400).json({error:"Caption is too long"});if(location!==undefined&&(location!==null&&(typeof location!=="string"||location.length>200)))return res.status(400).json({error:"Invalid location"});if(hashtags!==undefined&&(hashtags!==null&&(typeof hashtags!=="string"||hashtags.length>1000)))return res.status(400).json({error:"Invalid hashtags"});try{const [post]=await db.update(postsTable).set({caption:caption===undefined?undefined:(typeof caption==="string"?caption.trim():""),location:location===undefined?undefined:(typeof location==="string"?location.trim()||null:null),hashtags:hashtags===undefined?undefined:(typeof hashtags==="string"?hashtags.trim()||null:null),updatedAt:new Date()}).where(and(eq(postsTable.id,id),eq(postsTable.userId,req.userId!))).returning();return post?res.json({post}):res.status(404).json({error:"Post not found"});}catch(e){return dbError(res,e);}});
async function toggle(req:AuthedRequest,postId:number,field:"liked"|"saved"|"shared"|"reported"){const ex=await engagementFor(req.userId!,postId);if(!ex){const [row]=await db.insert(postEngagementsTable).values({postId,userId:req.userId!,[field]:true,updatedAt:new Date()}).returning();return {active:true,previous:false,row};}const active=!Boolean(ex[field]);const [row]=await db.update(postEngagementsTable).set({[field]:active,updatedAt:new Date()}).where(eq(postEngagementsTable.id,ex.id)).returning();return {active,previous:Boolean(ex[field]),row};}
async function updateScore(id:number){await refreshDistribution(id).catch(()=>undefined);}
for (const [path, field] of [["/posts/:id/like","liked"],["/posts/:id/save","saved"],["/posts/:id/report","reported"]] as const) { postsRouter.post(path,authMiddleware,async(req:AuthedRequest,res)=>{const id=postIdFrom(req,res);if(!id)return;try{const [target]=await db.select({userId:postsTable.userId}).from(postsTable).where(eq(postsTable.id,id)).limit(1);if(!target)return res.status(404).json({error:"Post not found"});const r=await toggle(req,id,field);const delta=r.active&&!r.previous?1:!r.active&&r.previous?-1:0;const column=field==="liked"?postsTable.likes:field==="reported"?postsTable.reports:postsTable.saves;const columnName=field==="liked"?"likes":field==="reported"?"reports":"saves";const [post]=await db.update(postsTable).set({[columnName]:sql`GREATEST(${column}+${delta},0)`,updatedAt:new Date()}).where(eq(postsTable.id,id)).returning();await updateScore(id);if(field==="liked")await createNotification(target.userId,req.userId!,"like",id,"Your post was liked.");return res.json({active:r.active,post});}catch(e){return dbError(res,e);}}); }
postsRouter.post("/posts/:id/share",authMiddleware,async(req:AuthedRequest,res)=>{const id=postIdFrom(req,res);if(!id)return;try{const [target]=await db.select({userId:postsTable.userId}).from(postsTable).where(eq(postsTable.id,id)).limit(1);if(!target)return res.status(404).json({error:"Post not found"});const [post]=await db.update(postsTable).set({shares:sql`${postsTable.shares}+1`,updatedAt:new Date()}).where(eq(postsTable.id,id)).returning();await updateScore(id);await createNotification(target.userId,req.userId!,"share",id,"Your post was shared.");return res.json({shared:true,post});}catch(e){return dbError(res,e);}});
postsRouter.post("/posts/:id/view",authMiddleware,async(req:AuthedRequest,res)=>{const id=postIdFrom(req,res);if(!id)return;try{const [post]=await db.update(postsTable).set({views:sql`${postsTable.views}+1`,updatedAt:new Date()}).where(eq(postsTable.id,id)).returning({id:postsTable.id,views:postsTable.views});if(!post)return res.status(404).json({error:"Post not found"});await updateScore(id);return res.json({viewed:true,post});}catch(e){return dbError(res,e);}});
postsRouter.get("/posts/:id/comments",authMiddleware,async(req,res)=>{const id=postIdFrom(req,res);if(!id)return;try{const [post]=await db.select({id:postsTable.id}).from(postsTable).where(eq(postsTable.id,id)).limit(1);if(!post)return res.status(404).json({error:"Post not found"});return res.json({comments:await db.select().from(commentsTable).where(eq(commentsTable.postId,id)).orderBy(desc(commentsTable.createdAt)).limit(100)});}catch(e){return dbError(res,e);}});
postsRouter.post("/posts/:id/comments",authMiddleware,async(req:AuthedRequest,res)=>{const postId=postIdFrom(req,res);if(!postId)return;const text=textField(req.body?.text,2000,true);if(text===null)return res.status(400).json({error:"Comment text is required and must be 2000 characters or less"});try{const [target]=await db.select({userId:postsTable.userId}).from(postsTable).where(eq(postsTable.id,postId)).limit(1);if(!target)return res.status(404).json({error:"Post not found"});const [comment]=await db.insert(commentsTable).values({postId,userId:req.userId!,text}).returning();await db.update(postsTable).set({comments:sql`${postsTable.comments}+1`}).where(eq(postsTable.id,postId));await updateScore(postId);await createNotification(target.userId,req.userId!,"comment",postId,"Your post received a new comment.");return res.status(201).json({comment});}catch(e){return dbError(res,e);}});
postsRouter.delete("/posts/:id",authMiddleware,async(req:AuthedRequest,res)=>{const id=postIdFrom(req,res);if(!id)return;try{const [p]=await db.delete(postsTable).where(and(eq(postsTable.id,id),eq(postsTable.userId,req.userId!))).returning({id:postsTable.id});return p?res.json({success:true}):res.status(404).json({error:"Post not found"});}catch(e){return dbError(res,e);}});
export default postsRouter;