import { Router } from "express";
import bcrypt from "bcryptjs";
import { db } from "@workspace/db";
import { usersTable } from "@workspace/db/schema";
import { eq } from "drizzle-orm";
import { authMiddleware, setSessionCookie, signToken } from "../middlewares/auth";
import { rateLimit } from "../middlewares/rate-limit";
import { optionalUrl, textField } from "../middlewares/validation";
const authRouter = Router();
const authLimiter = rateLimit({ windowMs: 60_000, max: 10, message: "Too many authentication attempts. Please wait a minute." });
function dbError(res: any, err: unknown) { console.error("[auth] database error", err); return res.status(500).json({ error: "Server error" }); }
function validUsername(value: unknown): string | null { if (typeof value !== "string") return null; const username=value.trim().toLowerCase(); return username.length>=3&&username.length<=30&&/^[a-z0-9._]+$/.test(username)?username:null; }
function avatarValue(value: unknown): string | null { if (value == null || value === "") return null; if (typeof value !== "string") return null; if (value.length > 1_500_000) return null; const url = optionalUrl(value, 500); if (url) return url; if (/^data:image\/(?:jpeg|jpg|png|webp|gif);base64,[A-Za-z0-9+/]+={0,2}$/.test(value)) return value; return null; }
authRouter.get("/auth/check-username/:username",authLimiter,async(req,res)=>{const username=validUsername(req.params["username"]);if(!username)return res.json({available:false,reason:"invalid_username"});try{const rows=await db.select({id:usersTable.id}).from(usersTable).where(eq(usersTable.username,username)).limit(1);return res.json({available:rows.length===0});}catch(err){return dbError(res,err);}});
authRouter.post("/auth/register",authLimiter,async(req,res)=>{const body=req.body;if(!body||typeof body!=="object"||Array.isArray(body))return res.status(400).json({error:"Invalid request body"});const {username,displayName,password,country,countryFlag,age,avatarUrl}=body as Record<string,unknown>;const u=validUsername(username);const d=textField(displayName,80,true);if(!u||!d||typeof password!=="string")return res.status(400).json({error:"Username, display name and password are required"});if(typeof username!=="string"||username.trim().toLowerCase()!==u)return res.status(400).json({error:"Invalid username"});if(password.length<6||password.length>200)return res.status(400).json({error:"Password must be 6-200 characters"});if(age!=null&&(!Number.isSafeInteger(age)||(age as number)<13||(age as number)>120))return res.status(400).json({error:"Invalid age"});if(country!=null&&(typeof country!=="string"||country.trim().length>80))return res.status(400).json({error:"Invalid country"});if(countryFlag!=null&&(typeof countryFlag!=="string"||countryFlag.length>16))return res.status(400).json({error:"Invalid country flag"});const avatar=avatarValue(avatarUrl);if(avatarUrl!=null&&avatarUrl!==""&&!avatar)return res.status(400).json({error:"Invalid avatar URL"});try{const existing=await db.select({id:usersTable.id}).from(usersTable).where(eq(usersTable.username,u)).limit(1);if(existing.length>0)return res.status(409).json({error:"Username already taken"});const passwordHash=await bcrypt.hash(password,12);const [user]=await db.insert(usersTable).values({username:u,displayName:d,passwordHash,country:typeof country==="string"?country.trim()||null:null,countryFlag:typeof countryFlag==="string"?countryFlag||null:null,age:typeof age==="number"?age:null,avatarUrl:avatar??null,bio:""}).returning();if(!user)return res.status(500).json({error:"Unable to create user"});const token=signToken(user.id);setSessionCookie(res,token);const {passwordHash:_,...publicUser}=user;return res.status(201).json({token,user:publicUser});}catch(err){return dbError(res,err);}});
authRouter.post("/auth/login",authLimiter,async(req,res)=>{const body=req.body;if(!body||typeof body!=="object"||Array.isArray(body))return res.status(400).json({error:"Invalid request body"});const {username,password}=body as Record<string,unknown>;if(typeof username!=="string"||typeof password!=="string"||!username.trim()||!password)return res.status(400).json({error:"Username and password are required"});const u=validUsername(username);if(!u||password.length>200)return res.status(401).json({error:"Invalid username or password"});try{const [user]=await db.select().from(usersTable).where(eq(usersTable.username,u)).limit(1);if(!user||!(await bcrypt.compare(password,user.passwordHash)))return res.status(401).json({error:"Invalid username or password"});const token=signToken(user.id);setSessionCookie(res,token);const {passwordHash:_,...publicUser}=user;return res.json({token,user:publicUser});}catch(err){return dbError(res,err);}});
authRouter.get("/auth/me",authMiddleware,async(req,res)=>{try{const userId=(req as any).userId as number;const [user]=await db.select().from(usersTable).where(eq(usersTable.id,userId)).limit(1);if(!user)return res.status(404).json({error:"User not found"});const {passwordHash:_,...publicUser}=user;return res.json(publicUser);}catch(err){return dbError(res,err);}});
authRouter.patch("/auth/me",authMiddleware,async(req,res)=>{const userId=(req as any).userId as number;const body=req.body;if(!body||typeof body!=="object"||Array.isArray(body))return res.status(400).json({error:"Invalid request body"});const {displayName,bio,website,country,countryFlag,avatarUrl}=body as Record<string,unknown>;const updates:Record<string,unknown>={};if(displayName!==undefined){const d=textField(displayName,80,true);if(!d)return res.status(400).json({error:"Invalid display name"});updates["displayName"]=d;}if(bio!==undefined){if(typeof bio!=="string"||bio.length>2000)return res.status(400).json({error:"Bio is too long"});updates["bio"]=bio;}if(website!==undefined){const url=optionalUrl(website,500);if(website!==null&&website!==""&&!url)return res.status(400).json({error:"Invalid website"});updates["website"]=url;}if(country!==undefined){if(country!==null&&(typeof country!=="string"||country.trim().length>80))return res.status(400).json({error:"Invalid country"});updates["country"]=typeof country==="string"?country.trim()||null:null;}if(countryFlag!==undefined){if(countryFlag!==null&&(typeof countryFlag!=="string"||countryFlag.length>16))return res.status(400).json({error:"Invalid country flag"});updates["countryFlag"]=typeof countryFlag==="string"?countryFlag||null:null;}if(avatarUrl!==undefined){const url=avatarValue(avatarUrl);if(avatarUrl!==null&&avatarUrl!==""&&!url)return res.status(400).json({error:"Invalid avatar URL"});updates["avatarUrl"]=url;}if(!Object.keys(updates).length)return res.status(400).json({error:"No fields to update"});try{const [user]=await db.update(usersTable).set(updates).where(eq(usersTable.id,userId)).returning();if(!user)return res.status(404).json({error:"User not found"});const {passwordHash:_,...publicUser}=user;return res.json(publicUser);}catch(err){return dbError(res,err);}});
authRouter.post("/auth/change-password",authMiddleware,authLimiter,async(req,res)=>{const userId=(req as any).userId as number;const body=req.body;if(!body||typeof body!=="object"||Array.isArray(body))return res.status(400).json({error:"Invalid request body"});const {currentPassword,newPassword}=body as Record<string,unknown>;if(typeof currentPassword!=="string"||typeof newPassword!=="string")return res.status(400).json({error:"Current and new passwords are required"});if(newPassword.length<6||newPassword.length>200)return res.status(400).json({error:"Password must be 6-200 characters"});try{const [user]=await db.select({passwordHash:usersTable.passwordHash}).from(usersTable).where(eq(usersTable.id,userId)).limit(1);if(!user||!(await bcrypt.compare(currentPassword,user.passwordHash)))return res.status(401).json({error:"Current password is incorrect"});await db.update(usersTable).set({passwordHash:await bcrypt.hash(newPassword,12)}).where(eq(usersTable.id,userId));return res.json({success:true});}catch(err){return dbError(res,err);}});
authRouter.post("/auth/reset-password",authLimiter,async(_req,res)=>res.status(410).json({error:"Password reset is temporarily unavailable. Use Change Password while signed in."}));
export default authRouter;
