import { Router, Request } from "express";
import { and, desc, eq, gt, inArray } from "drizzle-orm";
import { db } from "@workspace/db";
import { callsTable, callSignalsTable, usersTable } from "@workspace/db/schema";
import { authMiddleware } from "../middlewares/auth";
import { rateLimit } from "../middlewares/rate-limit";
const router=Router(); type R=Request&{userId?:number};
const CALL_STATUSES=["ringing","connecting","active","ended","rejected"] as const;
const SIGNAL_TYPES=["offer","answer","candidate","hangup"] as const;
function validUserId(value:unknown){const id=Number(value);return Number.isSafeInteger(id)&&id>0?id:null;}
function callIdValue(value:unknown){return typeof value==="string"&&value.length>0?value:null;}
const callLimiter=rateLimit({windowMs:60_000,max:60,message:"Too many call actions. Please slow down."});
router.use(callLimiter);
router.post("/calls/session",authMiddleware,async(req:R,res)=>{try{const targetUserId=validUserId(req.body?.targetUserId),kind=req.body?.kind==="video"?"video":"voice";if(!targetUserId||targetUserId===req.userId)return res.status(400).json({error:"Invalid target user"});const [target]=await db.select({id:usersTable.id}).from(usersTable).where(eq(usersTable.id,targetUserId)).limit(1);if(!target)return res.status(404).json({error:"Target user not found"});const id=`call_${Date.now()}_${req.userId}_${targetUserId}`;const [call]=await db.insert(callsTable).values({id,callerId:req.userId!,targetUserId,kind,status:"ringing"}).returning();return res.status(201).json({call})}catch(e){console.error(e);return res.status(500).json({error:"Server error"})}});
async function callRowsFor(userId:number){const outgoing=await db.select({id:callsTable.id,callerId:callsTable.callerId,targetUserId:callsTable.targetUserId,kind:callsTable.kind,status:callsTable.status,startedAt:callsTable.startedAt,endedAt:callsTable.endedAt,createdAt:callsTable.createdAt,callerUsername:usersTable.username,callerDisplayName:usersTable.displayName,callerAvatar:usersTable.avatarUrl}).from(callsTable).innerJoin(usersTable,eq(usersTable.id,callsTable.callerId)).where(eq(callsTable.callerId,userId)).orderBy(desc(callsTable.createdAt)).limit(100);const incoming=await db.select({id:callsTable.id,callerId:callsTable.callerId,targetUserId:callsTable.targetUserId,kind:callsTable.kind,status:callsTable.status,createdAt:callsTable.createdAt,callerUsername:usersTable.username,callerDisplayName:usersTable.displayName,callerAvatar:usersTable.avatarUrl}).from(callsTable).innerJoin(usersTable,eq(usersTable.id,callsTable.callerId)).where(eq(callsTable.targetUserId,userId)).orderBy(desc(callsTable.createdAt)).limit(100);const targetIds=Array.from(new Set(outgoing.map(c=>c.targetUserId)));const targets=targetIds.length?await db.select({id:usersTable.id,username:usersTable.username,displayName:usersTable.displayName,avatarUrl:usersTable.avatarUrl}).from(usersTable).where(inArray(usersTable.id,targetIds)):[];const targetMap=new Map(targets.map(u=>[u.id,u]));return [...outgoing.map(c=>({...c,targetUsername:targetMap.get(c.targetUserId)?.username??null,targetDisplayName:targetMap.get(c.targetUserId)?.displayName??null,targetAvatar:targetMap.get(c.targetUserId)?.avatarUrl??null})),...incoming].sort((a,b)=>+new Date(b.createdAt)-+new Date(a.createdAt)).slice(0,100)}
router.get("/calls/history",authMiddleware,async(req:R,res)=>{try{return res.json({calls:await callRowsFor(req.userId!)})}catch(e){console.error(e);return res.status(500).json({error:"Server error"})}});
router.get("/calls/incoming",authMiddleware,async(req:R,res)=>{try{const calls=await db.select({id:callsTable.id,callerId:callsTable.callerId,targetUserId:callsTable.targetUserId,kind:callsTable.kind,status:callsTable.status,createdAt:callsTable.createdAt,callerUsername:usersTable.username,callerDisplayName:usersTable.displayName,callerAvatar:usersTable.avatarUrl}).from(callsTable).innerJoin(usersTable,eq(usersTable.id,callsTable.callerId)).where(and(eq(callsTable.targetUserId,req.userId!),eq(callsTable.status,"ringing"))).orderBy(desc(callsTable.createdAt)).limit(5);return res.json({calls})}catch(e){console.error(e);return res.status(500).json({error:"Server error"})}});
router.get("/calls/:id/signals",authMiddleware,async(req:R,res)=>{try{const id=callIdValue(req.params.id);const after=Number(req.query.after??0);if(!id)return res.status(400).json({error:"Invalid call id"});if(!Number.isSafeInteger(after)||after<0)return res.status(400).json({error:"Invalid signal cursor"});const [call]=await db.select().from(callsTable).where(eq(callsTable.id,id));if(!call||(call.callerId!==req.userId&&call.targetUserId!==req.userId))return res.status(404).json({error:"Call not found"});const signals=await db.select().from(callSignalsTable).where(and(eq(callSignalsTable.callId,id),gt(callSignalsTable.id,after))).orderBy(callSignalsTable.id).limit(100);return res.json({signals})}catch(e){console.error(e);return res.status(500).json({error:"Server error"})}});
router.post("/calls/:id/signal",authMiddleware,async(req:R,res)=>{try{const id=callIdValue(req.params.id);if(!id)return res.status(400).json({error:"Invalid call id"});const [call]=await db.select().from(callsTable).where(eq(callsTable.id,id));if(!call||(call.callerId!==req.userId&&call.targetUserId!==req.userId))return res.status(404).json({error:"Call not found"});if(!req.body?.signal)return res.status(400).json({error:"Signal required"});const type=String(req.body.type??"candidate");if(!SIGNAL_TYPES.includes(type as typeof SIGNAL_TYPES[number]))return res.status(400).json({error:"Invalid signal type"});const serialized=JSON.stringify(req.body.signal);if(serialized.length>100_000)return res.status(413).json({error:"Signal payload too large"});const [row]=await db.insert(callSignalsTable).values({callId:id,senderId:req.userId!,type,payload:serialized}).returning();return res.status(201).json({accepted:true,signal:row})}catch(e){console.error(e);return res.status(500).json({error:"Server error"})}});
router.patch("/calls/:id",authMiddleware,async(req:R,res)=>{try{const id=callIdValue(req.params.id);if(!id)return res.status(400).json({error:"Invalid call id"});const status=String(req.body?.status??"");if(!CALL_STATUSES.includes(status as typeof CALL_STATUSES[number]))return res.status(400).json({error:"Invalid call status"});const [call]=await db.select().from(callsTable).where(eq(callsTable.id,id));if(!call||(call.callerId!==req.userId&&call.targetUserId!==req.userId))return res.status(404).json({error:"Call not found"});const [updated]=await db.update(callsTable).set({status:status as typeof CALL_STATUSES[number],startedAt:status==="active"?new Date():call.startedAt,endedAt:["ended","rejected"].includes(status)?new Date():call.endedAt}).where(eq(callsTable.id,id)).returning();if(["ended","rejected"].includes(status)&&!["ended","rejected"].includes(String(call.status))){await db.insert(callSignalsTable).values({callId:id,senderId:req.userId!,type:"hangup",payload:JSON.stringify({status})}).catch(()=>undefined);}return res.json({call:updated})}catch(e){console.error(e);return res.status(500).json({error:"Server error"})}});
export default router;
