import { Router, Request } from "express";
import { db } from "@workspace/db";
import { usersTable, postsTable, postEngagementsTable, followsTable, notificationsTable, conversationsTable, conversationMembersTable, messagesTable } from "@workspace/db/schema";
import { and, desc, eq, exists, ilike, or, sql } from "drizzle-orm";
import { authMiddleware } from "../middlewares/auth";
import { positiveId, textField, optionalUrl } from "../middlewares/validation";
import { rateLimit } from "../middlewares/rate-limit";
const socialRouter=Router();type AuthedRequest=Request&{userId?:number};
const dbError=(res:any,err:unknown)=>{console.error(err);return res.status(500).json({error:"Server error"})};
const publicUser={id:usersTable.id,username:usersTable.username,displayName:usersTable.displayName,country:usersTable.country,countryFlag:usersTable.countryFlag,age:usersTable.age,avatarUrl:usersTable.avatarUrl,bio:usersTable.bio,website:usersTable.website,createdAt:usersTable.createdAt};
const messageLimiter=rateLimit({windowMs:60_000,max:60,message:"Too many messages. Please slow down."});
const conversationLimiter=rateLimit({windowMs:60_000,max:20,message:"Too many conversation actions. Please slow down."});
async function notify(userId:number,actorId:number,type:string,message:string){if(userId!==actorId)await db.insert(notificationsTable).values({userId,actorId,type,message}).catch(()=>undefined)}

socialRouter.get("/users/search",authMiddleware,async(req:AuthedRequest,res)=>{let q=String(req.query.q??"").trim().toLowerCase();if(q.startsWith("@"))q=q.slice(1).trim();if(q.length<1)return res.json({users:[],posts:[]});if(q.length>80)return res.status(400).json({error:"Search query is too long"});try{const users=await db.select(publicUser).from(usersTable).where(or(ilike(usersTable.username,`%${q}%`),ilike(usersTable.displayName,`%${q}%`))).limit(25);const posts=await db.select({id:postsTable.id,userId:postsTable.userId,caption:postsTable.caption,mediaUrl:postsTable.mediaUrl,mediaType:postsTable.mediaType,likes:postsTable.likes,comments:postsTable.comments,createdAt:postsTable.createdAt}).from(postsTable).where(or(ilike(postsTable.caption,`%${q}%`),ilike(postsTable.hashtags,`%${q}%`))).orderBy(desc(postsTable.createdAt)).limit(25);return res.json({users,posts})}catch(e){return dbError(res,e)}});

socialRouter.get("/users/:id",authMiddleware,async(req:AuthedRequest,res)=>{const id=positiveId(req.params.id);if(!id)return res.status(400).json({error:"Invalid user id"});try{const [user]=await db.select(publicUser).from(usersTable).where(eq(usersTable.id,id)).limit(1);if(!user)return res.status(404).json({error:"User not found"});const [[followers],[following],[postCount],[isFollowing]]=await Promise.all([db.select({count:sql<number>`count(*)::int`}).from(followsTable).where(eq(followsTable.followingId,id)),db.select({count:sql<number>`count(*)::int`}).from(followsTable).where(eq(followsTable.followerId,id)),db.select({count:sql<number>`count(*)::int`}).from(postsTable).where(eq(postsTable.userId,id)),db.select({id:followsTable.id}).from(followsTable).where(and(eq(followsTable.followerId,req.userId!),eq(followsTable.followingId,id))).limit(1)]);const posts=await db.select().from(postsTable).where(eq(postsTable.userId,id)).orderBy(desc(postsTable.createdAt)).limit(60);return res.json({user:{...user,followers:followers?.count??0,following:following?.count??0,posts:postCount?.count??0,isFollowing:Boolean(isFollowing)},posts})}catch(e){return dbError(res,e)}});

socialRouter.post("/users/:id/follow",authMiddleware,async(req:AuthedRequest,res)=>{const followingId=positiveId(req.params.id);if(!followingId||followingId===req.userId)return res.status(400).json({error:"Invalid user id"});try{const [recipient]=await db.select({id:usersTable.id}).from(usersTable).where(eq(usersTable.id,followingId)).limit(1);if(!recipient)return res.status(404).json({error:"User not found"});await db.insert(followsTable).values({followerId:req.userId!,followingId}).onConflictDoNothing();await notify(followingId,req.userId!,"follow","You have a new follower.");return res.json({following:true})}catch(e){return dbError(res,e)}});
socialRouter.delete("/users/:id/follow",authMiddleware,async(req:AuthedRequest,res)=>{const followingId=positiveId(req.params.id);if(!followingId||followingId===req.userId)return res.status(400).json({error:"Invalid user id"});try{await db.delete(followsTable).where(and(eq(followsTable.followerId,req.userId!),eq(followsTable.followingId,followingId)));return res.json({following:false})}catch(e){return dbError(res,e)}});

socialRouter.get("/notifications",authMiddleware,async(req:AuthedRequest,res)=>{try{const notifications=await db.select({id:notificationsTable.id,type:notificationsTable.type,postId:notificationsTable.postId,storyId:notificationsTable.storyId,message:notificationsTable.message,readAt:notificationsTable.readAt,createdAt:notificationsTable.createdAt,actorId:usersTable.id,actorDisplayName:usersTable.displayName,actorUsername:usersTable.username,actorAvatarUrl:usersTable.avatarUrl}).from(notificationsTable).leftJoin(usersTable,eq(notificationsTable.actorId,usersTable.id)).where(eq(notificationsTable.userId,req.userId!)).orderBy(desc(notificationsTable.createdAt)).limit(50);return res.json({notifications})}catch(e){return dbError(res,e)}});
socialRouter.patch("/notifications/:id/read",authMiddleware,async(req:AuthedRequest,res)=>{const id=positiveId(req.params.id);if(!id)return res.status(400).json({error:"Invalid notification id"});try{const [notification]=await db.update(notificationsTable).set({readAt:new Date()}).where(and(eq(notificationsTable.id,id),eq(notificationsTable.userId,req.userId!))).returning();return notification?res.json({notification}):res.status(404).json({error:"Notification not found"})}catch(e){return dbError(res,e)}});

socialRouter.get("/conversations",authMiddleware,async(req:AuthedRequest,res)=>{try{const rows=await db.select({id:conversationsTable.id,updatedAt:conversationsTable.updatedAt,memberUserId:conversationMembersTable.userId,username:usersTable.username,displayName:usersTable.displayName,avatarUrl:usersTable.avatarUrl}).from(conversationsTable).innerJoin(conversationMembersTable,eq(conversationMembersTable.conversationId,conversationsTable.id)).innerJoin(usersTable,eq(usersTable.id,conversationMembersTable.userId)).where(exists(db.select({id:conversationMembersTable.id}).from(conversationMembersTable).where(and(eq(conversationMembersTable.conversationId,conversationsTable.id),eq(conversationMembersTable.userId,req.userId!))))).orderBy(desc(conversationsTable.updatedAt)).limit(100);const ids=[...new Set(rows.map(r=>r.id))];const conversations=await Promise.all(ids.map(async id=>{const other=rows.find(r=>r.id===id&&r.memberUserId!==req.userId);const [last]=await db.select({body:messagesTable.body,createdAt:messagesTable.createdAt}).from(messagesTable).where(eq(messagesTable.conversationId,id)).orderBy(desc(messagesTable.createdAt)).limit(1);return{id,userId:other?.memberUserId??0,username:other?.username??"",displayName:other?.displayName??"Unknown",avatarUrl:other?.avatarUrl??null,lastMessage:last?.body??"",lastMessageTime:last?.createdAt??null,unread:0,isOnline:false}}));return res.json({conversations})}catch(e){return dbError(res,e)}});
socialRouter.post("/conversations",authMiddleware,conversationLimiter,async(req:AuthedRequest,res)=>{const otherUserId=positiveId(req.body?.userId);if(!otherUserId||otherUserId===req.userId)return res.status(400).json({error:"Invalid recipient"});try{const [recipient]=await db.select({id:usersTable.id}).from(usersTable).where(eq(usersTable.id,otherUserId)).limit(1);if(!recipient)return res.status(404).json({error:"Recipient not found"});const [conversation]=await db.insert(conversationsTable).values({updatedAt:new Date()}).returning();await db.insert(conversationMembersTable).values([{conversationId:conversation.id,userId:req.userId!},{conversationId:conversation.id,userId:otherUserId}]);return res.status(201).json({conversation})}catch(e){return dbError(res,e)}});
socialRouter.get("/conversations/:id/messages",authMiddleware,async(req:AuthedRequest,res)=>{const id=positiveId(req.params.id);if(!id)return res.status(400).json({error:"Invalid conversation id"});try{const [member]=await db.select().from(conversationMembersTable).where(and(eq(conversationMembersTable.conversationId,id),eq(conversationMembersTable.userId,req.userId!))).limit(1);if(!member)return res.status(404).json({error:"Conversation not found"});const messages=await db.select().from(messagesTable).where(eq(messagesTable.conversationId,id)).orderBy(desc(messagesTable.createdAt)).limit(100);return res.json({messages:messages.reverse()})}catch(e){return dbError(res,e)}});
socialRouter.post("/conversations/:id/messages",authMiddleware,messageLimiter,async(req:AuthedRequest,res)=>{const id=positiveId(req.params.id);if(!id)return res.status(400).json({error:"Invalid conversation id"});const bodyText=req.body?.body;const mediaUrl=req.body?.mediaUrl;const kind=req.body?.kind;const durationMs=req.body?.durationMs;const body=bodyText===undefined?"":textField(bodyText,4000);if(body===null)return res.status(400).json({error:"Message is too long or invalid"});if(mediaUrl!==undefined&&mediaUrl!==null&&typeof mediaUrl!=="string")return res.status(400).json({error:"Invalid media URL"});const normalizedMediaUrl=typeof mediaUrl==="string"?optionalUrl(mediaUrl,2000):null;if(typeof mediaUrl==="string"&&!normalizedMediaUrl)return res.status(400).json({error:"Invalid media URL"});if(kind!==undefined&&kind!==null&&!['text','image','video','audio'].includes(String(kind)))return res.status(400).json({error:"Invalid message kind"});if(durationMs!==undefined&&durationMs!==null&&(typeof durationMs!=="number"||!Number.isSafeInteger(durationMs)||(durationMs as number)<0||(durationMs as number)>86_400_000))return res.status(400).json({error:"Invalid duration"});if(!body&&!normalizedMediaUrl)return res.status(400).json({error:"Message text or media required"});try{const [member]=await db.select().from(conversationMembersTable).where(and(eq(conversationMembersTable.conversationId,id),eq(conversationMembersTable.userId,req.userId!))).limit(1);if(!member)return res.status(404).json({error:"Conversation not found"});const [message]=await db.insert(messagesTable).values({conversationId:id,senderId:req.userId!,body,mediaUrl:normalizedMediaUrl,kind:kind??(normalizedMediaUrl?"image":"text"),durationMs:durationMs??null}).returning();await db.update(conversationsTable).set({updatedAt:new Date()}).where(eq(conversationsTable.id,id));return res.status(201).json({message})}catch(e){return dbError(res,e)}});

for (const [path, column, whereColumn] of [["/users/:id/followers","followerId","followingId"],["/users/:id/following","followingId","followerId"]] as const) { socialRouter.get(path,authMiddleware,async(req,res)=>{const id=positiveId(req.params.id);if(!id)return res.status(400).json({error:"Invalid user id"});try{const users=await db.select(publicUser).from(followsTable).innerJoin(usersTable,eq(usersTable.id,followsTable[column])).where(eq(followsTable[whereColumn],id)).orderBy(desc(followsTable.createdAt)).limit(100);return res.json({users})}catch(e){return dbError(res,e)}}); }

socialRouter.get("/posts/saved",authMiddleware,async(req:AuthedRequest,res)=>{try{const rows=await db.select().from(postsTable).innerJoin(postEngagementsTable,eq(postEngagementsTable.postId,postsTable.id)).where(and(eq(postEngagementsTable.userId,req.userId!),eq(postEngagementsTable.saved,true))).orderBy(desc(postsTable.createdAt)).limit(100);return res.json({posts:rows.map(r=>r.posts)})}catch(e){return dbError(res,e)}});
export default socialRouter;
