import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { ArrowLeft, Archive } from "lucide-react";
import { apiJson } from "@/lib/api";
import { t } from "@/lib/i18n";
import BottomNav from "@/components/BottomNav";

type Archived={id:number;userId:number;username:string;displayName:string;avatarUrl:string|null;archivedAt:string};
export default function ArchivedChats(){const[,setLocation]=useLocation();const[conversations,setConversations]=useState<Archived[]>([]);const[loading,setLoading]=useState(true);useEffect(()=>{apiJson<{conversations:Archived[]}>("/conversations/archived").then(d=>setConversations(d.conversations??[])).catch(()=>setConversations([])).finally(()=>setLoading(false));},[]);const restore=async(id:number)=>{const ok=await apiJson(`/conversations/${id}/archive`,{method:"DELETE"}).then(()=>true).catch(()=>false);if(ok)setConversations(prev=>prev.filter(c=>c.id!==id));};return <div className="w-full max-w-[430px] mx-auto min-h-screen bg-background pb-20"><header className="sticky top-0 z-40 px-4 py-4 flex items-center gap-3" style={{background:"rgba(13,11,20,0.95)",backdropFilter:"blur(20px)",borderBottom:"1px solid rgba(255,255,255,0.06)"}} data-testid="archived-header"><button onClick={()=>setLocation("/messages")} data-testid="btn-back-archived"><ArrowLeft size={22} className="text-white/80"/></button><h1 className="text-base font-semibold text-white">{t("archivedChats")}</h1></header><div className="px-4 py-4">{loading?<p className="text-white/40 text-sm text-center py-20">Loading...</p>:conversations.length===0?<div className="flex flex-col items-center justify-center py-24 gap-3"><Archive size={48} className="text-white/20"/><p className="text-white/40 text-sm">No archived chats</p><p className="text-white/25 text-xs px-8 text-center">Swipe left on a conversation and tap Archive to move it here</p></div>:conversations.map(c=><div key={c.id} className="flex items-center gap-3 py-3.5" style={{borderBottom:"1px solid rgba(255,255,255,0.05)"}}><img src={c.avatarUrl||`https://api.dicebear.com/8.x/initials/svg?seed=${encodeURIComponent(c.displayName)}`} alt={c.displayName} className="w-12 h-12 rounded-full object-cover"/><div className="flex-1 min-w-0"><p className="text-white font-semibold text-sm">{c.displayName}</p><p className="text-white/40 text-xs">@{c.username}</p></div><button onClick={()=>restore(c.id)} className="px-4 py-1.5 rounded-full text-sm font-semibold text-white" style={{background:"rgba(255,255,255,0.1)",border:"1px solid rgba(255,255,255,0.15)"}}>Restore</button></div>)}</div><BottomNav/></div>}
