import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { ArrowLeft, PhoneIncoming, PhoneOutgoing, PhoneMissed, Phone, Video } from "lucide-react";
import { apiJson } from "@/lib/api";
import { t } from "@/lib/i18n";
import BottomNav from "@/components/BottomNav";

type Call={id:string;callerId:number;targetUserId:number;kind:"voice"|"video";status:string;startedAt:string|null;endedAt:string|null;createdAt:string;callerUsername:string;callerDisplayName:string;callerAvatar:string|null;targetUsername:string|null;targetDisplayName:string|null;targetAvatar:string|null};
export default function CallHistory(){const[,setLocation]=useLocation();const[calls,setCalls]=useState<Call[]>([]);const[loading,setLoading]=useState(true);useEffect(()=>{apiJson<{calls:Call[]}>("/calls/history").then(d=>setCalls(d.calls??[])).catch(()=>setCalls([])).finally(()=>setLoading(false));},[]);const duration=(c:Call)=>{if(!c.startedAt||!c.endedAt)return"—";const s=Math.max(0,Math.round((new Date(c.endedAt).getTime()-new Date(c.startedAt).getTime())/1000));return`${Math.floor(s/60)}:${String(s%60).padStart(2,"0")}`};return <div className="w-full max-w-[430px] mx-auto min-h-screen bg-background pb-20"><header className="sticky top-0 z-40 px-4 py-4 flex items-center gap-3" style={{background:"rgba(13,11,20,.95)",backdropFilter:"blur(20px)",borderBottom:"1px solid rgba(255,255,255,.06)"}} data-testid="call-history-header"><button onClick={()=>setLocation("/messages")} data-testid="btn-back-call-history"><ArrowLeft size={22} className="text-white/80"/></button><h1 className="text-base font-semibold text-white">{t("callHistory")}</h1></header><div data-testid="call-log">{loading?<p className="text-white/40 text-sm text-center py-20">Loading...</p>:calls.length===0?<p className="text-white/40 text-sm text-center py-20">No calls yet</p>:calls.map(call=>{const incoming=call.targetUserId!==call.callerId;const missed=call.status==="rejected"&&incoming;const userId=incoming?call.callerId:call.targetUserId;const name=incoming?call.callerDisplayName:call.targetDisplayName;const avatar=incoming?call.callerAvatar:call.targetAvatar;return <button key={call.id} onClick={()=>setLocation(`/${call.kind}-call/${userId}`)} className="w-full flex items-center gap-3 px-4 py-3.5 text-left" style={{borderBottom:"1px solid rgba(255,255,255,.05)"}} data-testid={`call-${call.id}`}><img src={avatar||`https://api.dicebear.com/8.x/initials/svg?seed=${encodeURIComponent(name||"Unknown user")}`} alt={name||"Unknown user"} className="w-11 h-11 rounded-full object-cover"/><div className="flex-1 min-w-0"><p className="text-white font-semibold text-sm">{name||"Unknown user"}</p><div className="flex items-center gap-1.5 mt-0.5">{missed?<PhoneMissed size={13} className="text-red-400"/>:incoming?<PhoneIncoming size={13} className="text-green-400"/>:<PhoneOutgoing size={13} className="text-blue-400"/>}<span className={`text-xs ${missed?"text-red-400":"text-white/50"}`}>{missed?"Missed":incoming?"Incoming":"Outgoing"} · {duration(call)}</span><span className="text-white/30 text-xs">· {new Date(call.createdAt).toLocaleString()}</span></div></div><div className="w-9 h-9 rounded-full flex items-center justify-center" style={{background:"rgba(255,0,110,.12)",border:"1px solid rgba(255,0,110,.25)"}}>{call.kind==="video"?<Video size={16} className="text-pink-400"/>:<Phone size={16} className="text-pink-400"/>}</div></button>})}</div><BottomNav/></div>}
