export type Lang = "en" | "fr" | "es" | "mg";
export type LanguageOption = { code: Lang; name: string; flag: string };

export const availableLanguages: LanguageOption[] = [
  { code: "en", name: "English", flag: "🇬🇧" },
  { code: "fr", name: "Français", flag: "🇫🇷" },
  { code: "es", name: "Español", flag: "🇪🇸" },
  { code: "mg", name: "Malagasy", flag: "🇲🇬" },
];

const common = {
  followers:"Followers", following:"Following", follow:"Follow", unfollow:"Unfollow", yourStory:"Your Story",
  noStories:"No stories available", noMessages:"No messages", addFriends:"Add friends", loadingMore:"Loading more…",
  unreadMessages:"unread messages", newPost:"New Post", back:"Back", savePost:"Save post", sharePost:"Share post",
  loading:"Loading…", noResults:"No results", noFollowers:"No followers yet", noFollowing:"Not following anyone yet",
  posts:"Posts", comments:"Comments", likes:"Likes", saved:"Saved", send:"Send", reply:"Reply", close:"Close",
  delete:"Delete", edit:"Edit", report:"Report", retry:"Retry", createPost:"Create post", createStory:"Create story",
  searchUsers:"Search users", searching:"Searching…", noUsersFound:"No users found", discoverSearch:"Discover people and content by searching.",
  followersLabel:"followers", verified:"Verified", unread:"unread", loadingFollowers:"Loading followers…", loadingFollowing:"Loading following…"
};

const translations: Record<Lang, Record<string, string>> = {
  en: { ...common, home:"Home", notifications:"Notifications", messages:"Messages", profile:"Profile", search:"Search", create:"Create", worldFeed:"World Feed", settings:"Settings", language:"Language", appearance:"Appearance", privacy:"Privacy", security:"Security", storage:"Storage", about:"About", logout:"Log Out", logoutConfirm:"Are you sure you want to log out?", cancel:"Cancel", confirm:"Confirm", darkMode:"Dark Mode", lightMode:"Light Mode", blockedUsers:"Blocked Users", verify:"Verify Account", twoFactor:"Two-Factor Authentication", activeSessions:"Active Sessions", loginHistory:"Login History", cacheManagement:"Clear Cache", downloadData:"Download My Data", helpCenter:"Help Center", feedback:"Send Feedback", termsOfService:"Terms of Service", privacyPolicy:"Privacy Policy", appVersion:"App Version", deleteAccount:"Delete Account" },
  fr: { ...common, followers:"Abonnés", following:"Abonnements", follow:"Suivre", unfollow:"Ne plus suivre", yourStory:"Votre story", noStories:"Aucune story disponible", noMessages:"Aucun message", addFriends:"Ajouter des amis", loadingMore:"Chargement…", unreadMessages:"messages non lus", newPost:"Nouvelle publication", back:"Retour", savePost:"Enregistrer", sharePost:"Partager", loading:"Chargement…", noResults:"Aucun résultat", noFollowers:"Aucun abonné pour le moment", noFollowing:"Aucun abonnement pour le moment", posts:"Publications", comments:"Commentaires", likes:"J'aime", saved:"Enregistrés", send:"Envoyer", reply:"Répondre", close:"Fermer", delete:"Supprimer", edit:"Modifier", report:"Signaler", retry:"Réessayer", createPost:"Créer une publication", createStory:"Créer une story", searchUsers:"Rechercher des utilisateurs", searching:"Recherche…", noUsersFound:"Aucun utilisateur trouvé", discoverSearch:"Découvrez des personnes et du contenu en effectuant une recherche.", followersLabel:"abonnés", verified:"Vérifié", unread:"non lus", loadingFollowers:"Chargement des abonnés…", loadingFollowing:"Chargement des abonnements…", home:"Accueil", notifications:"Notifications", messages:"Messages", profile:"Profil", search:"Recherche", create:"Créer", worldFeed:"Fil mondial", settings:"Paramètres", language:"Langue", appearance:"Apparence", privacy:"Confidentialité", security:"Sécurité", storage:"Stockage", about:"À propos", logout:"Déconnexion", logoutConfirm:"Voulez-vous vraiment vous déconnecter ?", cancel:"Annuler", confirm:"Confirmer", darkMode:"Mode sombre", lightMode:"Mode clair", blockedUsers:"Utilisateurs bloqués", verify:"Vérifier le compte", twoFactor:"Authentification à deux facteurs", activeSessions:"Sessions actives", loginHistory:"Historique de connexion", cacheManagement:"Vider le cache", downloadData:"Télécharger mes données", helpCenter:"Centre d'aide", feedback:"Envoyer un commentaire", termsOfService:"Conditions d'utilisation", privacyPolicy:"Politique de confidentialité", appVersion:"Version de l'application", deleteAccount:"Supprimer le compte" },
  es: { ...common, followers:"Seguidores", following:"Siguiendo", follow:"Seguir", unfollow:"Dejar de seguir", yourStory:"Tu historia", noStories:"No hay historias", noMessages:"No hay mensajes", addFriends:"Añadir amigos", loadingMore:"Cargando…", unreadMessages:"mensajes sin leer", newPost:"Nueva publicación", back:"Atrás", savePost:"Guardar", sharePost:"Compartir", loading:"Cargando…", noResults:"Sin resultados", noFollowers:"Aún no hay seguidores", noFollowing:"No sigues a nadie", posts:"Publicaciones", comments:"Comentarios", likes:"Me gusta", saved:"Guardados", send:"Enviar", reply:"Responder", close:"Cerrar", delete:"Eliminar", edit:"Editar", report:"Reportar", retry:"Reintentar", createPost:"Crear publicación", createStory:"Crear historia", searchUsers:"Buscar usuarios", searching:"Buscando…", noUsersFound:"No se encontraron usuarios", discoverSearch:"Descubre personas y contenido mediante la búsqueda.", followersLabel:"seguidores", verified:"Verificado", unread:"sin leer", loadingFollowers:"Cargando seguidores…", loadingFollowing:"Cargando seguidos…", home:"Inicio", notifications:"Notificaciones", messages:"Mensajes", profile:"Perfil", search:"Buscar", create:"Crear", worldFeed:"Feed mundial", settings:"Ajustes", language:"Idioma", appearance:"Apariencia", privacy:"Privacidad", security:"Seguridad", storage:"Almacenamiento", about:"Acerca de", logout:"Cerrar sesión", logoutConfirm:"¿Seguro que quieres cerrar sesión?", cancel:"Cancelar", confirm:"Confirmar", darkMode:"Modo oscuro", lightMode:"Modo claro", blockedUsers:"Usuarios bloqueados", verify:"Verificar cuenta", twoFactor:"Autenticación en dos pasos", activeSessions:"Sesiones activas", loginHistory:"Historial de inicio", cacheManagement:"Limpiar caché", downloadData:"Descargar mis datos", helpCenter:"Centro de ayuda", feedback:"Enviar comentarios", termsOfService:"Términos de servicio", privacyPolicy:"Política de privacidad", appVersion:"Versión de la app", deleteAccount:"Eliminar cuenta" },
  mg: { ...common, followers:"Mpanaraka", following:"Arahin-ko", follow:"Araho", unfollow:"Aza arahina intsony", yourStory:"Story-nao", noStories:"Tsy misy story", noMessages:"Tsy misy hafatra", addFriends:"Hanampy namana", loadingMore:"Mampiditra…", unreadMessages:"hafatra tsy voavaky", newPost:"Lahatsoratra vaovao", back:"Hiverina", savePost:"Tehirizo", sharePost:"Zarao", loading:"Mampiditra…", noResults:"Tsy misy valiny", noFollowers:"Tsy mbola misy mpanaraka", noFollowing:"Tsy manaraka olona ianao", posts:"Lahatsoratra", comments:"Fanehoan-kevitra", likes:"J'aime", saved:"Voatahiry", send:"Alefa", reply:"Valio", close:"Akatona", delete:"Fafao", edit:"Ovay", report:"Tatero", retry:"Andramo indray", createPost:"Mamorona lahatsoratra", createStory:"Mamorona story", searchUsers:"Mitadiava mpampiasa", searching:"Mitady…", noUsersFound:"Tsy nahita mpampiasa", discoverSearch:"Mitadiava olona sy votoaty amin'ny fikarohana.", followersLabel:"mpanaraka", verified:"Voamarina", unread:"tsy voavaky", loadingFollowers:"Mampiditra mpanaraka…", loadingFollowing:"Mampiditra olona arahina…", home:"Fandraisana", notifications:"Fampandrenesana", messages:"Hafatra", profile:"Profil", search:"Fikarohana", create:"Mamorona", worldFeed:"Feed maneran-tany", settings:"Fikirana", language:"Fiteny", appearance:"Endrika", privacy:"Tsiambaratelo", security:"Fiarovana", storage:"Fitahirizana", about:"Momba", logout:"Hivoaka", logoutConfirm:"Te hivoaka tokoa ve ianao?", cancel:"Hanafoana", confirm:"Hanamarina", darkMode:"Maody maizina", lightMode:"Maody mazava", blockedUsers:"Mpampiasa voasakana", verify:"Hamarino ny kaonty", twoFactor:"Fanamarinana dingana roa", activeSessions:"Session mavitrika", loginHistory:"Tantaran'ny fidirana", cacheManagement:"Hamafa cache", downloadData:"Hisintona ny angonako", helpCenter:"Foibe fanampiana", feedback:"Handefa hevitra", termsOfService:"Fepetra fampiasana", privacyPolicy:"Politikan'ny tsiambaratelo", appVersion:"Dikan'ny app", deleteAccount:"Hamafa kaonty" }
};

const LANGUAGE_KEY = "yuniko-language";
export function getLang(): Lang {
  if (typeof window === "undefined") return "en";
  const saved = localStorage.getItem(LANGUAGE_KEY) as Lang | null;
  if (saved && saved in translations) return saved;
  const browser = (navigator.language || "en").split("-")[0] as Lang;
  return browser in translations ? browser : "en";
}
export function setLang(lang: Lang): void { if (typeof window !== "undefined" && lang in translations) localStorage.setItem(LANGUAGE_KEY, lang); }
export function t(key: string, lang: Lang = getLang()): string { return translations[lang]?.[key] ?? translations.en[key] ?? key.replace(/([a-z])([A-Z])/g,"$1 $2"); }
export function isLanguageTranslated(lang: Lang): boolean { return lang in translations; }
export default translations;
